#spring:
#  application:
#    name: base_spring_boot
#  datasource:
#    url: jdbc:mysql://localhost:3306/e_commerce?createDatabaseIfNotExist=true
#    username: root
#    password: mapyeugau110418
#  jooq:
#    sql-dialect: org.hibernate.dialect.MySQL8Dialect
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#
#jwt:
#  secret:
#    key: Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad
#  expired:
#    access: 864000
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: thaingocphat231@gmail.com
#    password: "qora aght jalw asiv"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#server:
#  port: 8085
#
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /docs
spring:
  application:
    name: base_spring_boot

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:e_commerce}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:mapyeugau110418}

  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:thaingocphat231@gmail.com}
    password: ${MAIL_PASSWORD:qora aght jalw asiv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    key: ${JWT_SECRET:Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad}
  expired:
    access: ${JWT_EXPIRATION:864000}

server:
  port: ${SERVER_PORT:8085}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
